@startuml

== load modules ==
activate main.js
main.js --/ tiplogic.js : require(tiplogic)
main.js --/ index.html : BrowserWindow.load(...)
deactivate main.js
activate index.html

index.html --/ indexrenderer.js : <scrip src="...">

== tip file loading ==
index.html -> index.html : form load complete event
activate index.html
index.html --/ indexrenderer.js : onFormLoadComplete()
activate indexrenderer.js
deactivate index.html
deactivate index.html

indexrenderer.js --/ main.js : ipc.send('main-window-loaded')
deactivate indexrenderer.js
activate main.js

main.js -> tiplogic.js : loadTips()
activate tiplogic.js
tiplogic.js -> tiplogic.js : readTipsFileIntoJsonObject()
loop for each tip in JSON Object
  tiplogic.js -> indexrenderer.js : windowToNotify.webContents.send('add-tip-from-file-event', jsonKey, jsonContent[jsonKey]);
end loop
activate indexrenderer.js
indexrenderer.js -> indexrenderer.js : addNewTipToUI(...)
activate indexrenderer.js
indexrenderer.js --/ index.html : add tip to <ul><li>
deactivate indexrenderer.js
tiplogic.js <-- indexrenderer.js
deactivate indexrenderer.js
main.js <-- tiplogic.js
deactivate tiplogic.js
deactivate main.js





@enduml
